-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO I JOIN REST_REVIEW  R ON (I.REST_ID = R.REST_ID)
WHERE ADDRESS LIKE '서울%'
GROUP BY I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC;

-- 리뷰 평균 점수(세번째 자리에서 반올림, 내림차순 -> 즐겨찾기 수 내림차순)